title: Mic Drop Results
remote_theme: just-the-docs/just-the-docs
color_scheme: darkroom

favicon_ico: "https://raw.githubusercontent.com/banz04/mic-drop-results/main/.github/assets/mdr/icon.ico"

aux_links:
  "Visit repo on GitHub":
    - "//github.com/banz04/mic-drop-results"

aux_links_new_tab: true
